### ISSUE TITLE
Live mode activation

### ISSUE THREAD

**Issue by KozyrevychYaroslav** [factorhouse/kpow#10]
**Version of Kpow**
factorhouse/kpow-ce:91.2.1

**Describe the issue**
I don't see live mode

**Additional context**
I need to change the default display time of data in a topic (1 hour). LIVE_MODE_PERIOD_MS does not change anything, LIVE_MODE_ENABLED is set to true.

**Comment by d-t-w** [comment]
Hi @KozyrevychYaroslav thanks for your message.

Live mode is a feature of our paid product only, if you would like to evaluate you can sign up for a trial here:

https://kpow.io/try/#standard
