### ISSUE TITLE
backup and restore

### ISSUE THREAD

**Issue by leonardotorresaltez** [factorhouse/kpow#12]
Hello,
do you have backup and restore documentation ?

Is it the Kpow stateless o it has to be in synch with his kpow topics?

regards,
Leonardo

**Comment by wavejumper** [comment]
Hi @leonardotorresaltez the community edition is completely in-memory. All snapshotted metrics and telemetry disappear after the container has exited.

Our paid product features retention of metrics which are persisted to internal Kafka topics.
