### ISSUE TITLE
impact to Kafka Clusters

### ISSUE THREAD

**Issue by leonardotorresaltez** [factorhouse/kpow#13]
What is the Kpow impact in Kafka Clusters environments?

In terms of cpu/memory. Do we need to escalate the brokers in resources to install it ?

regards,
Leonardo

**Comment by wavejumper** [comment]
Hi @leonardotorresaltez  - Kpow is a pretty light touch in terms of impact on Kafka clusters. The community edition in particular is all in-memory, so only the regular snapshotting that happens ever 1 minute using standard AdminClient API calls are the main impact. This impact is completely negligible to your overall brokers performance. 

Our paid version writes data to internal Kafka topics. We have had 4 years of experience in production with our customers (some of who have very large Kafka clusters) tuning down the topic configuration (retention, segment.ms etc) to ensure that all internal topics are low impact.

No customer (that we are aware of) has ever had to scale up brokers to use Kpow.
