### ISSUE TITLE
Headers are not persisted on duplication/copy

### ISSUE THREAD

**Issue by kanissh** [factorhouse/kpow#21]
**Version of Kpow**
Kpow-ce latest image from docker hub

**Describe the bug**
After a record is produced and it is copied or duplicated to be produced again, the newly duplicated record looses all the headers that were added in the first place (only key and value are available in the duplicated record). 

**To Reproduce**
1. Produce a record with headers.
2. Duplicate/copy the record to produce again.
3. See headers are not available in the duplicated record.
 
**Expected behavior**
When a produced record with headers is duplicated, it is expected to see the headers added in the produced record to be available in the newly duplicated record.

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Docker version: Docker desktop 4

**Comment by d-t-w** [comment]
Thanks @kanissh for your clear description and error report.

We can reproduce this bug and will fix it in the next release.

I will update this ticket when the release/fix is available.

**Comment by d-t-w** [comment]
This issue is fixed in kpow v92.3, which is available now in Dockerhub.

Thanks for the report.
