### ISSUE TITLE
license

### ISSUE THREAD

**Issue by intelligent002** [factorhouse/kpow#36]
**Version of Kpow**
The version of Kpow you are running
community latest docker

**Describe the issue**
A clear and concise description of the issue
emailed license is incorrect

**Additional context**
license:
License Certificate 8145ba1d-efcd-43ab-bb08-987c0d060c8e
--------BEGIN LICENSE CERTIFICATE-------
ID: 8145ba1d-efcd-43ab-bb08-987c0d060c8e
Type: Kpow Community
Licensee: Arkady Rosenberg
Expiry: 2025-12-16
Cluster Credits: 1

6AE01D67 C4F3A91B 324F43B4 661E3CC2
201144BA 587A3D91 1E87FF1F B4DC38AB
6ADA08AB 2806A5D8 6C13272C FF6ED863
AFAB9057 7A071149 F67DAFE4 30491D96
AF15F3A8 BD74D5B1 1DD3B113 FB10F072
5CE7C824 E1F58A5A 3D050EA7 572C4E47
D1DAB9BC E3B55032 A24E4892 06191500
2BE745E2 AF687D75 2FBAB2FF C41C2CCD
--------END LICENSE CERTIFICATE---------

.env file according to manual here - https://docs.factorhouse.io/kpow-ce/configuration/#license
## The Kafka Bootstrap URL for your cluster (Required).
BOOTSTRAP=10.1.3.24:9092,10.1.3.25:9092,10.1.3.26:9092

## These parameters can be cut/paste from your license email
LICENSE_ID=8145ba1d-efcd-43ab-bb08-987c0d060c8e
LICENSE_CODE=Kpow Community
LICENSEE=Arkady Rosenberg
LICENSE_EXPIRY=2025-12-16
LICENSE_SIGNATURE=6AE01D67C4F3A91B324F43B4661E3CC2201144BA587A3D911E87FF1FB4DC38AB6ADA08AB2806A5D86C13272CFF6ED863AFAB90577A071149F67DAFE430491D96AF15F3A8BD74D5B11DD3B113FB10F0725CE7C824E1F58A5A3D050EA7572C4E47D1DAB9BCE3B55032A24E4892061915002BE745E2AF687D752FBAB2FFC41C2CCD

output of container:
-- Installation ----------------------------------------------------------------
* Release: 93.4 (2024-08-20-15-00)
* Java Runtime: 17.0.12
* Product Type: Unlicensed
-- Components ------------------------------------------------------------------
~ ERROR vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
Exception starting Kpow. Please check your configuration:
- Failing component: [:kpow/license "details"]
- Inputs: 
  * code: 'Kpow Community'
  * id: '8145ba1d-efcd-43ab-bb08-987c0d060c8e'
  * licensee: 'Arkady Rosenberg'
  * expiry: '2025-12-16'
  * signature: '6AE01D67C4F3A91B324F43B4661E3CC2201144BA587A3D911E87FF1FB4DC38AB6ADA08AB2806A5D86C13272CFF6ED863AFAB90577A071149F67DAFE430491D96AF15F3A8BD74D5B11DD3B113FB10F0725CE7C824E1F58A5A3D050EA7572C4E47D1DAB9BCE3B55032A24E4892061915002BE745E2AF687D752FBAB2FFC41C2CCD'
- Message: license details incorrect
- Relevant documentation: https://docs.kpow.io/ce/configuration/#license
- Don't have a license? Visit https://kpow.io/get-started/ to get a free community license.

**Comment by intelligent002** [comment]
resolved, need to read the WHOLE email :)

**Comment by d-t-w** [comment]
Hey @intelligent002 thanks for raising the ticket anyway.

At a guess we should think of having the license environment variables at the top of the email rather than the certificate, I think that trips people up sometimes..
